### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by akien-mga** [MightyPrinny/GodotSpriteText#1]
On Godot's [Asset Library](https://godotengine.org/asset-library/asset/edit/1005) (sorry for the late review), you mentioned that this asset is under the MIT license, but there is no license text in this repository to confirm that.

Please add a LICENSE file with the MIT license text. See https://choosealicense.com

**Comment by MightyPrinny** [comment]
Thank you, I added the licence and updated the commit tag for the asset library.
